AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  Exclude:
    - bin/**/*
    - vendor/**/*

Style/AsciiComments:
  Enabled: false
  
Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/CollectionMethods:
  Enabled: true

Style/SymbolArray:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - config/**/*.rb

Style/BlockDelimiters:
  EnforcedStyle: line_count_based
  Exclude:
    - spec/**/*.rb

Metrics/LineLength:
  Max: 100
